import {BuilderDefinition} from "./Civilians/Builder";
import {CourierDefinition} from "./Civilians/Courier";
import {ExtractorDefinition} from "./Civilians/Extractor";
import {FillerDefinition} from "./Civilians/Filler";
import {HarvesterDefinition} from "./Civilians/Harvester";
import {JanitorDefinition} from "./Civilians/Janitor";
import {MinerDefinition} from "./Civilians/Miner";
import {SeederDefinition} from "./Civilians/Seeder";
import {UpgraderDefinition} from "./Civilians/Upgrader";
import {GuardianDefinition} from "./Military/Guardian";
import {MedicDefinition} from "./Military/Medic";
import {MissionaryDefinition} from "./Military/Missionary";
import {RaiderDefinition} from "./Military/Raider";

export const Builder = new BuilderDefinition();
export const Courier = new CourierDefinition();
export const Extractor = new ExtractorDefinition();
export const Filler = new FillerDefinition();
export const Harvester = new HarvesterDefinition();
export const Janitor = new JanitorDefinition();
export const Miner = new MinerDefinition();
export const Seeder = new SeederDefinition();
export const Upgrader = new UpgraderDefinition();
export const Guardian = new GuardianDefinition();
export const Medic = new MedicDefinition();
export const Missionary = new MissionaryDefinition();
export const Raider = new RaiderDefinition();
